ident = letter | digit { letter | digit }.

expression = "{" statement "}" {"," statement }.

statement = ident ":" "{" term { "," term }  "}".

term = (
    "'Size'" ":" INT
    | "'Type'" ":" ("'int'" | "'float'" | "'string'" | "'char'" | "'date'")
    | "'Mandatory'" ":" ("True"|"False")
    | "'AllowBlank'" ":" ("True"|"False")
    | "'Enum'" ":" "[" "'" ident "'" {"," "'" ident "'"} "]"
    | "'Composite'" ":" "[" "'" ident "'" {"," "'" ident "'"} "]"
    | "'Min'" ":" INT
    | "'Max'" ":" INT
    | "'Default'" ":" INT
    | "'Format'" ":" ident
    | "'Unique'" ":" ("True"|"False")
    | "'StartsWith'" ":" "[" "'" ident "'" {"," "'" ident "'"} "]"
    | "'Expression'" ":" ident
    ).
 
INT = digit { digit }.

    